# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-connect
#   namespace: default
# spec:
#   type: NodePort
#   ports:
#   - port: 8083
#     targetPort: 8083
#     nodePort: 31083
#   selector:
#     app: kafka-connect
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: default  # Replace with your namespace if different
spec:
  selector:
    app: kafka-connect  # Ensure this matches the label used in the deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
