apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-s3-config
  namespace: default
data:
  s3-sink-connector.json: |
    {
      "name": "s3-sink-connector",
      "config": {
        "connector.class": "io.confluent.connect.s3.S3SinkConnector",
        "tasks.max": "1",
        "topics": "biogroupit_gpss_schema_history",
        "s3.bucket.name": "kafka-sink",
        "s3.region": "us-east-1",
        "s3.part.size": "5242880",
        "flush.size": "3",
        "s3.endpoint": "http://minio-service.minio-namespace.svc.cluster.local:9000",
        "aws.access.key.id": "minioadmin",
        "aws.secret.access.key": "minioadmin",
        "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
        "storage.class": "io.confluent.connect.s3.storage.S3Storage",
        "schema.compatibility": "NONE"
      }
    }
